version: '3.12'

services:
  berrymore:
    image: berrymore
    container_name: berrymore
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - '.:/opt/app'
    ports:
      - ${LISTEN_PORT}:${LISTEN_PORT}
    depends_on:
      db:
        condition: service_healthy
    environment:
      LISTEN_HOST: ${LISTEN_HOST}
      LISTEN_PORT: ${LISTEN_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      DJANGO_ADMIN_PASSWORD: ${DJANGO_ADMIN_PASSWORD}

  db:
    image: postgres
    container_name: ${POSTGRES_HOST}
    restart: always
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 10
    command: -p ${POSTGRES_PORT}
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      PGUSER: ${POSTGRES_USER}
      PGPORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /var/lib/postgresql/data/
    volumes:
        - /var/lib/postgresql/data/:/var/lib/postgresql/data/

  adminer:
    image: adminer
    container_name: berrymore_adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  pgdata:
    driver: local
